### ISSUE TITLE
Problem: Unclear what a "Public Contract" is in this context

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/BEPs#10]
In 1/C4, [the section on "Evolution of Public Contracts"](https://github.com/bigchaindb/BEPs/tree/master/1#26-evolution-of-public-contracts) isn't clear what it means by "Public Contracts".

It _seems_ to be talking about BigchainDB Enhancement Proposals, BEPs, but it says that nowhere.

Or is a "Public Contract" something else? Is so, what?

If it's a BEP, can we just change the name in 1/C4 from "Public Contracts" to "BEPs" for clarity and consistency? We could even link to 2/COSS.

**Comment by vrde** [comment]
You are right, it's not clear.

From my understanding, a "Public Contract" should be equivalent to our [Public API](https://github.com/bigchaindb/bigchaindb/blob/master/CHANGELOG.md#change-log-release-notes) plus all our BEPs.

Does it make sense to you as well?

**Comment by ttmc** [comment]
Oh, our Public API... we can include that in the Public Contracts, yes.

Would it make sense to add a paragraph to the section on "Evolution of Public Contracts" to list the things included in the "Public Contracts": All BEPs, our Public API, maybe other things?

We could make a small BEP that specifies "what is in the BigchainDB Public API." Do you think that would make sense? It's weird having the Public API defined in the header of CHANGELOG.md.

**Comment by ttmc** [comment]
Some day, the HTTP API, the Events API, the BigchainDB Server CLI, the transaction model(s), and more can all be in BEPs.

We already have the transaction model as a nice spec document. I just need to find time to move that over to become BEPs (one BEP per transaction model version, I think). They are currently over at https://github.com/ipdb/ipdb-tx-spec

**Comment by vrde** [comment]
> Some day, the HTTP API, the Events API, the BigchainDB Server CLI, the transaction model(s), and more can all be in BEPs.

Agree, but this might take ∞ amount of time :fire_engine: 

What about improving section _2.1. Preliminaries_ with those new items:
- A "Public Contract" is a contract between the project and the end-user. It can be a BEP, an API, a Command Line Interface, or anything the end-user rely on.
- The project SHALL use [Semantic Versioning](https://semver.org/) (note: Public API is a Public Contract).

**Comment by ttmc** [comment]
To resolve this issue, see the comment:

https://github.com/bigchaindb/BEPs/pull/15#issuecomment-372589957
