### ISSUE TITLE
Problem: it's not clear how to number BEPs

### ISSUE THREAD

**Issue by vrde** [bigchaindb/BEPs#17]
In 2/COSS I find the following line:
> Every BEP (including branches) carries a different number. New versions of the same BEP have new numbers.

It's quite generic, and can lead to arbitrary decisions, what if I want to number my BEP something like *π*?

I see two different solutions to this problem:
1. the number is assigned right before merging, incrementing by 1 the value of the last BEP number; or
2. use the number of the PR.

I lean towards 2), because it's automatically assigned by the platform we are using, and it doesn't require coordination.

**Comment by codegeschrei** [comment]
I would say we go with number 2 since it's easier and still incremental. At some point when there are a lot of BEPs with different states you also don't see if there are numbers 'missing'.

**Comment by ttmc** [comment]
I would say duels every time.

**Comment by ttmc** [comment]
Realistically, the rate of BEP production will slow and it will be obvious what the next number is. In the rare case of a collision, it can be fixed, no big deal.

**Comment by muawiakh** [comment]
I agree with @ttmc , for example I won the last duel 🥇 because I can merge now, so I will number my change to `4` and @ttmc can resolve conflicts accordingly. Should be straight forward.

**Comment by vrde** [comment]
Let's keep it like this for now. I'll close this issue.
