### ISSUE TITLE
Use GitHub's new "code owners" feature to assign an owner to each BEP (subdirectory)?

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/BEPs#39]
GitHub introduced a new feature that lets you attach owners to files, directories, or the like:

https://blog.github.com/2017-07-06-introducing-code-owners/

Maybe we could try that to give each BEP (e.g. subdirectory such as `/5`) a code owner?

**Comment by codegeschrei** [comment]
For the BEPs it would be very useful, since the author is the one who should maintain everything related to their BEP.
