### ISSUE TITLE
Rename this repository?

### ISSUE THREAD

**Issue by ttmc** [bigchaindb/beps#4]
This repository is currently named "rfc" and the opening line on GitHub says "BigchainDB RFCs."

While using "RFC" is not _wrong_, it implies a lot of formality and expectations going back to 1969. We want something more lightweight here, I think, so we can move fast.

### Ideas

Rename this repository to:

- BigchainDB Enhancement Proposals (BEPs), similar to Python
- BigchainDB Improvement Proposals (BDBIPs, since BIPs is used already by Bitcoin)

If some of them become very stable and widely-used, then maybe they could be used as the starting point for _actual_ IETF RFCs, something like what Interledger did with some of its specs.

**Comment by vrde** [comment]
Thanks for those ideas. While I don't think "RFC" implies formality (the ZMQ community uses "RFC" as well), **BEPs** can also work for me.

@sbellem contacted me in private asking me about the name, he might want to be included in the conversation.

**Comment by ttmc** [comment]
Based on verbal discussions,  unless there are any reasonable objections, I think I will rename this repository to **BigchainDB Enhancement Proposals (BEPs)** with short name `bigchaindb/beps`.

Note: [GitHub redirects requests made to the old repository URLs](https://github.com/blog/1508-repository-redirects-are-here), so existing links shouldn't break.

**Comment by vrde** [comment]
OK, I'm changing the name now :)
