### ISSUE TITLE
Can transaction.data be a complex structure?

### ISSUE THREAD

**Issue by ppazos** [bigchaindb/BEPs#72]
I'm checking the specs, interested on using bigchaindb for health care applications, where clinical documentation is hierarchic (complex trees).

Seen the data spec and it seems a plain key-value list. Is is possible for that to be a general JSON document?

**Comment by ttmc** [comment]
- The value of `metadata` can be almost any associative array, where the value of some key can itself be an associative array, and so on recursively, so a hierarchical tree stucture is totally fine. The only limitations are on the overall transaction size, and some rules inherited from using MongoDB: https://github.com/bigchaindb/BEPs/tree/master/13#bigchaindb-server-deviations 

- Also, in CREATE transactions, the value of `asset.data` can be almost any associative array, just like `metadata` (with the same rules and caveats).

**Comment by ppazos** [comment]
Thanks. Being an associative array means being a normal json object? { ... }. What's the max transaction size? Can't find it on the referenced page.

**Comment by ttmc** [comment]
Most programming languages have their own way of implementing or supporting [associative arrays](https://en.wikipedia.org/wiki/Associative_array). In Python, they are called "dicts". In Java and Go, they are called "maps". The syntax for an associative array varies from language to language, but they all have one or more packages/libraries to convert the associative array into a JSON string, and they also have a way to convert a JSON string into an array of bytes, which is what gets sent over the wire.

Anyway, you shouldn't have to think about that when using BigchainDB. You should just be able to use your language's syntax for associative arrays, and then give that to a BigchainDB driver to do all the rest.

The max transaction size is determined either:

- by the BigchainDB network's `genesis.json` file (where it's one of the parameters; note that this is a Tendermint thing, not a BigchainDB-specific thing),
- by your network infrastructure (e.g. NGINX config file), or
- by MongoDB (which has a max BSON document size of 16 MB).

**Comment by ppazos** [comment]
@ttmc I know what an associative array is :) my question is regarding the use of bigchaindb and the JSON transaction, that is independent from any programming language and how associative arrays are implemented there. So regarding the specific JSON transaction, can the data be any JSON object? I mean a general tree with any depth level.

I'm looking at the test site https://www.bigchaindb.com/developers/getstarted/ where the transaction in JSON is shown, if I enter a JSON for the message, it is treated as a string and escaped.

I health care we need to store general JSON objects (trees) as an structure not as a string, is that possible?

On that page, I see the JS code and the data part is a simple object, but not sure if that can be a complex one.

```
const tx = driver.Transaction.makeCreateTransaction(
    { message: 'blablabla' },   <<<<<<<<<<<<<<<<<<<<<<
    null, ....
```

This is a sample structure in XML (we have canonical transformations to JSON so will be the same structure but in a JSON representation) https://github.com/ppazos/cabolabs-ehrserver/blob/master/versions/with_signature_49cbda33-5270-4f85-a714-8926338a937b.xml

16MB seems more than enough for clinical documentation, most clinical documents are less than 200 KB.

**Comment by ttmc** [comment]
The associative array can be a general tree of any depth, with values being strings, integers, the-equivalent-of-null, True, False, etc. One can't send an associative array, as is, over the wire. It has to be serialized into a sequence of bytes (or bits) first. BigchainDB's transaction spec says how you should do that:

1. serialize it into a JSON string in a very particular way, see https://github.com/bigchaindb/BEPs/tree/master/13#json-serialization-and-deserialization
2. encode that string to a sequence of bytes using UTF-8 encoding, see https://github.com/bigchaindb/BEPs/tree/master/13#converting-strings-to-bytes
